[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "dolt sql-server --host 0.0.0.1 --port 3306 --remotesapi addr=0.0.0.0:8080 --data-dir /data"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[volume]]
name = "dolt-data"
mountPath = "/data"
